name: Dependency Updates

on:
  schedule:
    # Run every Monday at 9 AM UTC
    - cron: "0 9 * * 1"
  workflow_dispatch: # Allow manual triggering

jobs:
  update-dependencies:
    name: Update Dependencies
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Use Node.js 18.x
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
          cache: "npm"
          cache-dependency-path: |
            client/package-lock.json
            server/package-lock.json

      - name: Update client dependencies
        working-directory: ./client
        run: |
          npm update
          npm audit fix --force || true

      - name: Update server dependencies
        working-directory: ./server
        run: |
          npm update
          npm audit fix --force || true

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore: update dependencies"
          title: "🔄 Automated Dependency Updates"
          body: |
            ## Automated Dependency Updates

            This PR contains automated dependency updates:

            ### Changes:
            - Updated npm dependencies to latest compatible versions
            - Applied security fixes where applicable

            ### Testing:
            - [ ] All tests pass
            - [ ] Application builds successfully
            - [ ] No breaking changes detected

            This PR was automatically created by the dependency update workflow.
          branch: chore/dependency-updates
          delete-branch: true
          labels: |
            dependencies
            automated
