name: Deploy Documentation

on:
  push:
    branches: [main]
    paths:
      - "docs/**"
      - "README.md"
      - ".github/workflows/docs.yml"
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-docs:
    name: Build Documentation
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
          cache: npm
          cache-dependency-path: |
            client/package-lock.json

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Install dependencies
        working-directory: ./client
        run: npm ci

      - name: Generate API documentation
        working-directory: ./client
        run: |
          # Generate TypeScript documentation
          npx typedoc --out ../docs/api src --exclude "**/*.test.ts" --exclude "**/*.spec.ts" || echo "TypeDoc not configured"

      - name: Build documentation site
        run: |
          mkdir -p _site
          cp README.md _site/index.md
          cp -r docs/* _site/ 2>/dev/null || echo "No docs directory found"

          # Create a simple HTML wrapper
          cat > _site/index.html << 'EOF'
          <!DOCTYPE html>
          <html>
          <head>
              <title>Hotel Management System Documentation</title>
              <meta charset="utf-8">
              <meta name="viewport" content="width=device-width, initial-scale=1">
              <style>
                  body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; max-width: 1200px; margin: 0 auto; padding: 20px; }
                  h1 { color: #2563eb; }
                  pre { background: #f1f5f9; padding: 1rem; border-radius: 8px; overflow-x: auto; }
                  code { background: #e2e8f0; padding: 0.2rem 0.4rem; border-radius: 4px; }
              </style>
          </head>
          <body>
              <h1>Hotel Management System Documentation</h1>
              <p>Welcome to the Hotel Management System documentation.</p>
              <h2>Quick Links</h2>
              <ul>
                  <li><a href="api/">API Documentation</a></li>
                  <li><a href="https://github.com/ed-terry/hotel-management-system">GitHub Repository</a></li>
              </ul>
              <div id="readme"></div>
              <script>
                  fetch('index.md')
                      .then(response => response.text())
                      .then(text => {
                          document.getElementById('readme').innerHTML = '<pre>' + text + '</pre>';
                      });
              </script>
          </body>
          </html>
          EOF

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./_site

  deploy:
    name: Deploy to GitHub Pages
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build-docs

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
